#!/usr/bin/python
"""
Generate C code & header for the list of slots

The output files will be overwritten. Commit them before running this.
"""

import re
import io
import sys
import csv
import argparse
import contextlib
import dataclasses
from pathlib import Path
from functools import partial


HERE = Path(__file__).parent

STRUCTS = {
    'tp_': ('PyTypeObject', None),
    'ht_': ('PyHeapTypeObject', None),
    'am_': ('PyAsyncMethods', 'tp_as_async'),
    'nb_': ('PyNumberMethods', 'tp_as_number'),
    'mp_': ('PyMappingMethods', 'tp_as_mapping'),
    'sq_': ('PySequenceMethods', 'tp_as_sequence'),
    'bf_': ('PyBufferProcs', 'tp_as_buffer'),
}

def generate_incfile(entries, outfile):
    output = partial(print, file=outfile)
    output("/* Generated by typeslots.py */")
    entries = entries.copy()
    for i in range(1, max(entries) + 1):
        if entry := entries.pop(i, None):
            member = entry.name
            output(entry.get_incfile_line())
        else:
            output("{0, 0},")

    if entries:
        raise ValueError(f'missing entries: {entries}')

def generate_header(entries, outfile):
    output = partial(print, file=outfile)
    output("/* Generated by typeslots.py */")
    added = None
    endif = None
    for entry in entries.values():
        if added != entry.added:
            if endif:
                output(endif)
            if entry.added:
                output('#if !defined(Py_LIMITED_API) || '
                    + f'Py_LIMITED_API+0 >= {entry.hex_added}')
                output(f'/* New in {entry.added} */')
                endif = '#endif'
            else:
                endif = None
        output(f'#define {entry.slot_name} {entry.number}')
    if endif:
        output(endif)


def filter_comments(file):
    for line in file:
        line = line.strip()
        if line and not line.startswith('#'):
            yield line

@dataclasses.dataclass
class Entry:
    number: int
    name: str
    data: dict

    def __getattr__(self, name):
        return self.get(name, None)

    def get(self, name, default=None):
        return self.data.get(name, default)

    @property
    def member_name(self):
        return self.data.get('member_name', self.name)

    @property
    def slot_name(self):
        return 'Py_' + self.name

    @property
    def hex_added(self):
        major, minor = self.added.split('.')
        return f'0x{int(major):02X}{int(minor):02X}0000'

    def get_incfile_line(self):
        table_type, table_name = STRUCTS[self.member_name[:3]]
        if table_name is None:
            member_offset = '-1'
            table_offset = f'offsetof({table_type}, {self.member_name})'
        else:
            member_offset = f'offsetof({table_type}, {self.member_name})'
            table_offset = f'offsetof(PyTypeObject, {table_name})'
        return '{%s, %s, _PyType_APPLY_%s},' % (
            member_offset, table_offset,
            self.get('apply', 'REJECT').upper(),
        )

def parse_input(file):
    result = {}
    for data in csv.reader(filter_comments(file)):
        number = int(data[0])
        if number in result:
            raise ValueError('dublicate number: {number} ({result[number]})')
        result[number] = Entry(
            int(data[0]),
            data[1].strip(),
            dict(pair.strip().split('=', 1) for pair in data[2:] if pair)
        )
    return result


def parse_args(context, argv):
    parser = argparse.ArgumentParser(prog=argv[0], description=__doc__)
    parser.add_argument('INCFILE', nargs='?',
                        default=HERE / 'typeslots.inc',
                        help="The .inc file for generated C code"
                        )
    parser.add_argument('HEADER', nargs='?',
                        default=HERE / '../Include/typeslots.h',
                        help="The .h file for generated C code")
    parser.add_argument('-i', '--input',
                        default=HERE / 'typeslots.txt',
                        help="The .csv file to read")

    args = parser.parse_args(argv[1:])
    args.header = context.enter_context(updating_file(args.HEADER))
    args.incfile = context.enter_context(updating_file(args.INCFILE))
    if args.input == '-':
        print(f'input: stdin', file=sys.stderr)
        args.input = sys.stdin
    else:
        path = Path(args.input).resolve()
        print(f'input: {path}', file=sys.stderr)
        file = Path(args.input).open(encoding='utf-8')
        args.input = context.enter_context(file)

    return args


@contextlib.contextmanager
def updating_file(path):
    """Open a temporary file that will replace *path* on success."""
    if path == '-':
        raise ValueError('"-" arguments not supported')
    else:
        path = Path(path).resolve()
        tmp_path = path.with_name(path.name + '.tmp')
        try:
            with tmp_path.open('w', encoding='utf-8') as file:
                yield file
            try:
                old_contents = path.read_text()
                new_contents = tmp_path.read_text()
            except FileNotFoundError:
                old_contents = None
                new_contents = 'not none'
            if old_contents != new_contents:
                print(f'writing: {path}', file=sys.stderr)
                tmp_path.replace(path)
            else:
                print(f'unchanged: {path}', file=sys.stderr)
        finally:
            tmp_path.unlink(missing_ok=True)


def main():
    with contextlib.ExitStack() as context:
        args = parse_args(context, sys.argv)
        entries = parse_input(args.input)
        generate_incfile(entries, args.incfile)
        generate_header(entries, args.header)

if __name__ == "__main__":
    main()
