#!/usr/bin/python
"""
Generate C code & header for the list of slots

The output files will be overwritten. Commit them before running this.
"""

import re
import io
import sys
import csv
import tomllib
import argparse
import contextlib
import dataclasses
from pathlib import Path
from functools import partial


HERE = Path(__file__).parent

STRUCTS = {
    'tp_': ('PyTypeObject', None),
    'ht_': ('PyHeapTypeObject', None),
    'am_': ('PyAsyncMethods', 'tp_as_async'),
    'nb_': ('PyNumberMethods', 'tp_as_number'),
    'mp_': ('PyMappingMethods', 'tp_as_mapping'),
    'sq_': ('PySequenceMethods', 'tp_as_sequence'),
    'bf_': ('PyBufferProcs', 'tp_as_buffer'),
}

C_CHAR_MAP = {
    **{i: f'\\x{i:02x}' for i in range(256)},
    **{i: chr(i) for i in range(32, 127)},
    ord('\n'): r'\n',
    ord('\t'): r'\t',
    ord('"'): r'\"',
    ord("'"): r"\'",
}

def c_str(string):
    return '"' + string.encode().decode('latin-1').translate(C_CHAR_MAP) + '"'

def generate_incfile(entries, outfile):
    output = partial(print, file=outfile)
    output("/* Generated by typeslots.py */")
    entries = entries.copy()
    for i in range(1, max(entries) + 1):
        if entry := entries.pop(i, None):
            member = entry.name
            output(entry.get_incfile_line())
        else:
            output("{0, 0},")

    if entries:
        raise ValueError(f'missing entries: {entries}')

def generate_header(entries, outfile):
    output = partial(print, file=outfile)
    output("/* Generated by typeslots.py */")
    prev_added = None
    endif = None
    for entry in entries.values():
        entry_added = entry.get('added')
        if prev_added != entry_added:
            if endif:
                output(endif)
            if entry_added:
                output('#if !defined(Py_LIMITED_API) || '
                    + f'Py_LIMITED_API+0 >= {entry.hex_added}')
                output(f'/* New in {entry_added} */')
                endif = '#endif'
            else:
                endif = None
        prev_added = entry_added
        output(f'#define {entry.slot_name} {entry.number}')
    if endif:
        output(endif)


def generate_incfile2(entries, outfile):
    output = partial(print, file=outfile)
    for entry in entries.values():
        parts = []
        parts.append(f'{c_str(entry.name)}')
        if entry.slot.startswith('tp_'):
            parts.append(f'offsetof(PyTypeObject, {entry.slot})')
        else:
            struct_member = STRUCTS[entry.slot[:3]][1][3:]
            parts.append(f'offsetof(PyHeapTypeObject, {struct_member}.{entry.slot})')
        parts.append(f'(void *)({entry.function})')
        parts.append(f'{entry.wrapper}')
        parts.append(f'PyDoc_STR({c_str(entry.full_docstring)})')
        if sp := entry.get('_split_doc'):
            if sp is True:
                parts[-1] = parts[-1].replace(r'--\n\n', r'--\n\n" "', 1)
            elif isinstance(sp, str):
                parts[-1] = f'" "{sp}" "'.join(parts[-1].rsplit(sp, 1))
            else:
                parts[-1] = parts[-1].replace(r'--\n\n', r'--\n\n" "', 1)
                a, b = sp
                c = a.replace(b, f'{b}" "')
                parts[-1] = parts[-1].replace(a, c)
        if sp := entry.get('_split_sig'):
            parts[-1] = parts[-1].replace(r'__(', r'__" "(', 1)
        if entry.flags:
            parts.append(entry.flags)
        parts.append(f'.name_strobj = &_Py_ID({entry.name})')
        output('    {', ', '.join(parts),
               ' ' if entry.get('_sp') else '',
               '},', sep='')


def filter_comments(file):
    for line in file:
        line = line.strip()
        if line and not line.startswith('#'):
            yield line

@dataclasses.dataclass
class Entry:
    number: int
    name: str
    data: dict

    def __getitem__(self, name):
        return self.data[name]

    def get(self, name, default=None):
        return self.data.get(name, default)

    @property
    def member_name(self):
        return self.get('member_name', self.name)

    @property
    def slot_name(self):
        return 'Py_' + self.name

    @property
    def hex_added(self):
        major, minor = self['added'].split('.')
        return f'0x{int(major):02X}{int(minor):02X}0000'

    def get_incfile_line(self):
        table_type, table_name = STRUCTS[self.member_name[:3]]
        if table_name is None:
            member_offset = '-1'
            table_offset = f'offsetof({table_type}, {self.member_name})'
        else:
            member_offset = f'offsetof({table_type}, {self.member_name})'
            table_offset = f'offsetof(PyTypeObject, {table_name})'
        items = [
            member_offset, table_offset,
            f'.name="{self.slot_name}"',
        ]
        if self.get('apply') == 'replace':
            items.append('.apply_replace=true')
        return '{' + ', '.join(items) + '},'

def parse_input(file):
    result = {}
    for data in csv.reader(filter_comments(file)):
        number = int(data[0])
        if number in result:
            raise ValueError('duplicate number: {number} ({result[number]})')
        result[number] = Entry(
            int(data[0]),
            data[1].strip(),
            dict(pair.strip().split('=', 1) for pair in data[2:] if pair)
        )
    return result

class Entry2:
    def __init__(self, name, data):
        self.name = name.partition('-')[0]
        self.data = data

    def __getitem__(self, name):
        return self.data[name]

    def get(self, name, default=None):
        return self.data.get(name, default)

    @property
    def slot(self):
        return self['slot']

    @property
    def function(self):
        return self.get('function', 'NULL')

    @property
    def wrapper(self):
        return self.get('wrapper', 'NULL')

    @property
    def signature(self):
        return self.get('signature', None)

    @property
    def docstring(self):
        return self.get('docstring', None)

    @property
    def full_docstring(self):
        parts = []
        if self.signature:
            parts.append(self.name + self.signature)
        if self.docstring:
            parts.append(self.docstring)
        return '\n--\n\n'.join(parts)

    @property
    def flags(self):
        return self.get('flags', None)


def parse_input2(file):
    data = tomllib.loads(file.read())
    return {name: Entry2(name, value) for name, value in data.items()}


def parse_args(context, argv):
    parser = argparse.ArgumentParser(prog=argv[0], description=__doc__)
    parser.add_argument('INCFILE', nargs='?',
                        default=HERE / 'typeslots.inc',
                        help="The .inc file for generated C code"
                        )
    parser.add_argument('HEADER', nargs='?',
                        default=HERE / '../Include/typeslots.h',
                        help="The .h file for generated C code")
    parser.add_argument('INCFILE2', nargs='?',
                        default=HERE / 'slotdefs.inc',
                        help="The .inc file for generated C code"
                        )
    parser.add_argument('-i', '--input',
                        default=HERE / 'typeslots.txt',
                        help="The .csv file to read")
    parser.add_argument('-I', '--input2',
                        default=HERE / 'slotdefs.txt',
                        help="The other file to read")

    args = parser.parse_args(argv[1:])
    args.header = context.enter_context(updating_file(args.HEADER))
    args.incfile = context.enter_context(updating_file(args.INCFILE))
    args.incfile2 = context.enter_context(updating_file(args.INCFILE2))
    for name in 'input', 'input2':
        if getattr(args, name) == '-':
            print(f'{name}: stdin', file=sys.stderr)
            setattr(args, name, sys.stdin)
        else:
            path = Path(getattr(args, name)).resolve()
            print(f'input: {path}', file=sys.stderr)
            file = path.open(encoding='utf-8')
            setattr(args, name, context.enter_context(file))

    return args


@contextlib.contextmanager
def updating_file(path):
    """Open a temporary file that will replace *path* on success."""
    if path == '-':
        raise ValueError('"-" arguments not supported')
    else:
        path = Path(path).resolve()
        tmp_path = path.with_name(path.name + '.tmp')
        try:
            with tmp_path.open('w', encoding='utf-8') as file:
                yield file
            try:
                old_contents = path.read_text()
                new_contents = tmp_path.read_text()
            except FileNotFoundError:
                old_contents = None
                new_contents = 'not none'
            if old_contents != new_contents:
                print(f'writing: {path}', file=sys.stderr)
                tmp_path.replace(path)
            else:
                print(f'unchanged: {path}', file=sys.stderr)
        finally:
            tmp_path.unlink(missing_ok=True)


def main():
    with contextlib.ExitStack() as context:
        args = parse_args(context, sys.argv)
        entries = parse_input(args.input)
        entries2 = parse_input2(args.input2)
        generate_incfile(entries, args.incfile)
        generate_incfile2(entries2, args.incfile2)
        generate_header(entries, args.header)

if __name__ == "__main__":
    main()
