#!/usr/bin/env python3.8
# @generated by pegen from Tools/stable_abi/stable_abi.gram

import ast
import sys
import tokenize

from typing import Any, Optional

from pegen.parser import memoize, memoize_left_rec, logger, Parser
import dataclasses
import typing

@dataclasses.dataclass
class StructInfo:
    name: str
    fields: typing.Iterable
    abi_only: bool = False

    @classmethod
    def make(cls, name, entries):
        fields = []
        changes = []
        abi_only = False
        for entry in entries:
            if isinstance(entry, FieldInfo):
                fields.append(entry)
            elif isinstance(entry, ChangeInfo):
                changes.append(ChangeInfo)
            elif isinstance(entry, AbiOnly):
                abi_only = True
            else:
                raise TypeError(type(entry))
        return cls(name, fields, abi_only)

@dataclasses.dataclass
class TypeInfo:
    pass

@dataclasses.dataclass
class ChangeInfo:
    type: str
    version_info: tuple
    
    @classmethod
    def make(cls, name, version_string):
        return cls(name, tuple(int(v) for v in version_string.split('.')))

@dataclasses.dataclass
class FieldInfo:
    name: str
    type: TypeInfo
    abi_only: bool = False

    @classmethod
    def make(cls, name, typ, entries=()):
        changes = []
        abi_only = False
        for entry in entries:
            if isinstance(entry, ChangeInfo):
                changes.append(ChangeInfo)
            elif isinstance(entry, AbiOnly):
                abi_only = True
            else:
                raise TypeError(type(entry))
        return cls(name, typ, abi_only)

@dataclasses.dataclass
class FunctionInfo:
    name: str
    abi_only: bool = False

    @classmethod
    def make(cls, name, entries=()):
        changes = []
        abi_only = False
        for entry in entries:
            if isinstance(entry, ChangeInfo):
                changes.append(ChangeInfo)
            elif isinstance(entry, AbiOnly):
                abi_only = True
            elif isinstance(entry, ArgInfo):
                pass
            elif isinstance(entry, ReturnInfo):
                pass
            else:
                raise TypeError(type(entry))
        return cls(name, abi_only)

@dataclasses.dataclass
class DataInfo:
    name: str
    abi_only: bool = False

    @classmethod
    def make(cls, name, entries=()):
        changes = []
        abi_only = False
        for entry in entries:
            if isinstance(entry, ChangeInfo):
                changes.append(ChangeInfo)
            elif isinstance(entry, AbiOnly):
                abi_only = True
            else:
                raise TypeError(type(entry))
        return cls(name, abi_only)

@dataclasses.dataclass
class TypedefInfo:
    name: str
    abi_only: bool = False

    @classmethod
    def make(cls, name, entries=()):
        changes = []
        abi_only = False
        for entry in entries:
            if isinstance(entry, ChangeInfo):
                changes.append(ChangeInfo)
            elif isinstance(entry, AbiOnly):
                abi_only = True
            else:
                raise TypeError(type(entry))
        return cls(name, abi_only)

@dataclasses.dataclass
class MacroInfo:
    name: str
    abi_only: bool = False

    @classmethod
    def make(cls, name, entries=()):
        changes = []
        abi_only = False
        for entry in entries:
            if isinstance(entry, ChangeInfo):
                changes.append(ChangeInfo)
            elif isinstance(entry, AbiOnly):
                abi_only = True
            else:
                raise TypeError(type(entry))
        return cls(name, abi_only)

@dataclasses.dataclass
class ArgInfo:
    name: str
    abi_only: bool = False

    @classmethod
    def make(cls, name, entries=()):
        changes = []
        abi_only = False
        for entry in entries:
            if isinstance(entry, ChangeInfo):
                changes.append(ChangeInfo)
            elif isinstance(entry, AbiOnly):
                abi_only = True
            else:
                raise TypeError(type(entry))
        return cls(name, abi_only)

@dataclasses.dataclass
class ReturnInfo:
    name: str
    abi_only: bool = False

    @classmethod
    def make(cls, name, entries=()):
        changes = []
        abi_only = False
        for entry in entries:
            if isinstance(entry, ChangeInfo):
                changes.append(ChangeInfo)
            elif isinstance(entry, AbiOnly):
                abi_only = True
            else:
                raise TypeError(type(entry))
        return cls(name, abi_only)


@dataclasses.dataclass
class AbiOnly:
    pass


@dataclasses.dataclass
class TypeName:
    name: str


@dataclasses.dataclass
class Pointer:
    qualifiers: list
    type: object

class GeneratedParser(Parser):

    @memoize
    def start(self) -> Optional[Any]:
        # start: entries $
        mark = self.mark()
        cut = False
        if (
            (entries := self.entries())
            and
            (endmarker := self.expect('ENDMARKER'))
        ):
            return entries
        self.reset(mark)
        if cut: return None
        return None

    @memoize_left_rec
    def entries(self) -> Optional[Any]:
        # entries: entries entry | entry
        mark = self.mark()
        cut = False
        if (
            (entries := self.entries())
            and
            (entry := self.entry())
        ):
            return entries + [ entry ]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (entry := self.entry())
        ):
            return [ entry ]
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def entry(self) -> Optional[Any]:
        # entry: struct | function | data | typedef | macro | change | abi_only | field | arg | returnspec
        mark = self.mark()
        cut = False
        if (
            (struct := self.struct())
        ):
            return struct
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (function := self.function())
        ):
            return function
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (data := self.data())
        ):
            return data
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (typedef := self.typedef())
        ):
            return typedef
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (macro := self.macro())
        ):
            return macro
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (change := self.change())
        ):
            return change
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (abi_only := self.abi_only())
        ):
            return abi_only
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (field := self.field())
        ):
            return field
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (arg := self.arg())
        ):
            return arg
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (ret := self.returnspec())
        ):
            return ret
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def struct(self) -> Optional[Any]:
        # struct: 'struct' NAME NEWLINE subentries?
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('struct'))
            and
            (name := self.name())
            and
            (newline := self.expect('NEWLINE'))
            and
            (e := self.subentries(),)
        ):
            return StructInfo . make ( name . string , e or [ ] )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def function(self) -> Optional[Any]:
        # function: 'function' ~ NAME NEWLINE subentries?
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('function'))
            and
            (cut := True)
            and
            (name := self.name())
            and
            (newline := self.expect('NEWLINE'))
            and
            (e := self.subentries(),)
        ):
            return FunctionInfo . make ( name . string , e or [ ] )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def data(self) -> Optional[Any]:
        # data: 'data' ~ NAME NEWLINE subentries?
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('data'))
            and
            (cut := True)
            and
            (name := self.name())
            and
            (newline := self.expect('NEWLINE'))
            and
            (e := self.subentries(),)
        ):
            return DataInfo . make ( name . string , e or [ ] )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def typedef(self) -> Optional[Any]:
        # typedef: 'typedef' ~ NAME NEWLINE subentries?
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('typedef'))
            and
            (cut := True)
            and
            (name := self.name())
            and
            (newline := self.expect('NEWLINE'))
            and
            (e := self.subentries(),)
        ):
            return TypedefInfo . make ( name . string , e or [ ] )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def macro(self) -> Optional[Any]:
        # macro: 'macro' ~ NAME NEWLINE subentries?
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('macro'))
            and
            (cut := True)
            and
            (name := self.name())
            and
            (newline := self.expect('NEWLINE'))
            and
            (e := self.subentries(),)
        ):
            return MacroInfo . make ( name . string , e or [ ] )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def subentries(self) -> Optional[Any]:
        # subentries: INDENT ~ entries DEDENT
        mark = self.mark()
        cut = False
        if (
            (indent := self.expect('INDENT'))
            and
            (cut := True)
            and
            (entries := self.entries())
            and
            (dedent := self.expect('DEDENT'))
        ):
            return entries
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def change(self) -> Optional[Any]:
        # change: 'added' ~ NUMBER NEWLINE | 'removed' ~ NUMBER NEWLINE
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('added'))
            and
            (cut := True)
            and
            (ver := self.number())
            and
            (newline := self.expect('NEWLINE'))
        ):
            return ChangeInfo . make ( 'added' , ver . string )
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('removed'))
            and
            (cut := True)
            and
            (ver := self.number())
            and
            (newline := self.expect('NEWLINE'))
        ):
            return ChangeInfo . make ( 'removed' , ver . string )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def field(self) -> Optional[Any]:
        # field: 'field' ~ c_declaration NEWLINE subentries?
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('field'))
            and
            (cut := True)
            and
            (c_declaration := self.c_declaration())
            and
            (newline := self.expect('NEWLINE'))
            and
            (e := self.subentries(),)
        ):
            return FieldInfo . make ( 'demo' , c_declaration , e or [ ] )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def abi_only(self) -> Optional[Any]:
        # abi_only: 'abi_only' ~ NEWLINE
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('abi_only'))
            and
            (cut := True)
            and
            (newline := self.expect('NEWLINE'))
        ):
            return AbiOnly ( )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def arg(self) -> Optional[Any]:
        # arg: 'arg' ~ c_declaration NEWLINE
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('arg'))
            and
            (cut := True)
            and
            (c_declaration := self.c_declaration())
            and
            (newline := self.expect('NEWLINE'))
        ):
            return ArgInfo . make ( c_declaration )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def returnspec(self) -> Optional[Any]:
        # returnspec: 'return' ~ c_declaration NEWLINE
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('return'))
            and
            (cut := True)
            and
            (c_declaration := self.c_declaration())
            and
            (newline := self.expect('NEWLINE'))
        ):
            return ReturnInfo . make ( c_declaration )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def c_declaration(self) -> Optional[Any]:
        # c_declaration: c_specqual c_declarator?
        mark = self.mark()
        cut = False
        if (
            (c_specqual := self.c_specqual())
            and
            (opt := self.c_declarator(),)
        ):
            return [c_specqual, opt]
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def c_specqual(self) -> Optional[Any]:
        # c_specqual: c_qualifier c_specqual | c_typespec
        mark = self.mark()
        cut = False
        if (
            (c_qualifier := self.c_qualifier())
            and
            (c_specqual := self.c_specqual())
        ):
            return [c_qualifier, c_specqual]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (c_typespec := self.c_typespec())
        ):
            return [c_typespec]
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def c_typespec(self) -> Optional[Any]:
        # c_typespec: 'void' | (('signed' | 'unsigned' | 'short' | 'long'))* ('int' | 'char' | 'float' | 'double') | NAME
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('void'))
        ):
            return TypeName ( 'void' )
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (_loop0_1 := self._loop0_1(),)
            and
            (name := self._tmp_2())
        ):
            return TypeName ( name )
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (name := self.name())
        ):
            return TypeName ( name . string )
        self.reset(mark)
        if cut: return None
        return None

    @memoize_left_rec
    def c_declarator(self) -> Optional[Any]:
        # c_declarator: NAME | c_pointerdecl | c_arraydecl | c_funcdecl | '(' c_declarator ')'
        mark = self.mark()
        cut = False
        if (
            (name := self.name())
        ):
            return name . string
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (c_pointerdecl := self.c_pointerdecl())
        ):
            return c_pointerdecl
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (c_arraydecl := self.c_arraydecl())
        ):
            return c_arraydecl
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (c_funcdecl := self.c_funcdecl())
        ):
            return c_funcdecl
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('('))
            and
            (c_declarator := self.c_declarator())
            and
            (literal_1 := self.expect(')'))
        ):
            return c_declarator
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def c_pointerdecl(self) -> Optional[Any]:
        # c_pointerdecl: '*' c_qualifier* c_declarator?
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('*'))
            and
            (q := self._loop0_3(),)
            and
            (d := self.c_declarator(),)
        ):
            return Pointer ( q , d )
        self.reset(mark)
        if cut: return None
        return None

    @logger
    def c_arraydecl(self) -> Optional[Any]:
        # c_arraydecl: c_declarator '[' NUMBER ']'
        mark = self.mark()
        cut = False
        if (
            (c_declarator := self.c_declarator())
            and
            (literal := self.expect('['))
            and
            (number := self.number())
            and
            (literal_1 := self.expect(']'))
        ):
            return [c_declarator, literal, number, literal_1]
        self.reset(mark)
        if cut: return None
        return None

    @logger
    def c_funcdecl(self) -> Optional[Any]:
        # c_funcdecl: c_declarator '(' c_params ')'
        mark = self.mark()
        cut = False
        if (
            (c_declarator := self.c_declarator())
            and
            (literal := self.expect('('))
            and
            (c_params := self.c_params())
            and
            (literal_1 := self.expect(')'))
        ):
            return ( c_declarator , '(' , c_params , ')' )
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def c_qualifier(self) -> Optional[Any]:
        # c_qualifier: 'const' | 'volatile' | 'restrict'
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('const'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('volatile'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('restrict'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def c_params(self) -> Optional[Any]:
        # c_params: 'void' | ','.c_declaration+ '...'?
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('void'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (_gather_4 := self._gather_4())
            and
            (opt := self.expect('...'),)
        ):
            return c_declaration
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def _loop0_1(self) -> Optional[Any]:
        # _loop0_1: ('signed' | 'unsigned' | 'short' | 'long')
        mark = self.mark()
        children = []
        cut = False
        while (
            (_tmp_6 := self._tmp_6())
        ):
            children.append([_tmp_6])
            mark = self.mark()
        self.reset(mark)
        if cut: return None
        return children

    @memoize
    def _tmp_2(self) -> Optional[Any]:
        # _tmp_2: 'int' | 'char' | 'float' | 'double'
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('int'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('char'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('float'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('double'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def _loop0_3(self) -> Optional[Any]:
        # _loop0_3: c_qualifier
        mark = self.mark()
        children = []
        cut = False
        while (
            (c_qualifier := self.c_qualifier())
        ):
            children.append([c_qualifier])
            mark = self.mark()
        self.reset(mark)
        if cut: return None
        return children

    @memoize
    def _loop0_5(self) -> Optional[Any]:
        # _loop0_5: ',' c_declaration
        mark = self.mark()
        children = []
        cut = False
        while (
            (literal := self.expect(','))
            and
            (elem := self.c_declaration())
        ):
            children.append(elem)
            mark = self.mark()
        self.reset(mark)
        if cut: return None
        return children

    @memoize
    def _gather_4(self) -> Optional[Any]:
        # _gather_4: c_declaration _loop0_5
        mark = self.mark()
        cut = False
        if (
            (elem := self.c_declaration())
            is not None
            and
            (seq := self._loop0_5())
            is not None
        ):
            return [elem] + seq
        self.reset(mark)
        if cut: return None
        return None

    @memoize
    def _tmp_6(self) -> Optional[Any]:
        # _tmp_6: 'signed' | 'unsigned' | 'short' | 'long'
        mark = self.mark()
        cut = False
        if (
            (literal := self.expect('signed'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('unsigned'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('short'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        cut = False
        if (
            (literal := self.expect('long'))
        ):
            return [literal]
        self.reset(mark)
        if cut: return None
        return None


if __name__ == '__main__':
    from pegen.parser import simple_parser_main
    simple_parser_main(GeneratedParser)
