#ifndef _Py_PYCORE_SLOTS_H
#define _Py_PYCORE_SLOTS_H

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

#define _PySlot_TYPE_VOID 1
#define _PySlot_TYPE_FUNC 2
#define _PySlot_TYPE_PTR 3
#define _PySlot_TYPE_XINT64 4
#define _PySlot_TYPE_ARRAY 5

#define _PySlot_KIND_TYPE 1
#define _PySlot_KIND_MOD 2
#define _PySlot_KIND_COMPAT 0x100
#define _PySlot_KIND_SLOT 0x200

typedef struct {
    const char *name;
    uint8_t dtype;
    union {
        struct {
            /* For type slots (_PySlot_KIND_TYPE):
             * Most slots corresponds to members in PyTypeObject & similar
             * structs.
             * ach entry has two offsets, "slot_offset" and "subslot_offset".
             * If is subslot_offset is -1, slot_offset is an offset within the
             * PyTypeObject struct.
             * Otherwise slot_offset is an offset to a pointer to a sub-slots
             * struct (such as "tp_as_number"), and subslot_offset is the
             * offset within that struct.
             *
             * If subslot_offset is zero, the slot needs special handling;
             * the offset mechanism isn't used.
             */
            short subslot_offset;
            short slot_offset;
        } type_info;
        struct {
            /* For compat slots (_PySlot_KIND_COMPAT):
             * these slots were renumbered; `type_id` is the ID of the new
             * type slot; `mod_id` of the module slot.
             */
            short type_id;
            short mod_id;
        } compat_info;
    }
} _PySlot_Info;

// The actual table is generated by a script.
extern const _PySlot_Info _PySlot_InfoTable[];

#define _PySlot_MAX_RECURSION 5;

typedef struct {
    union {
        PySlot *slot;
        PyType_Slot *tp_slot;
        PyModuleDef_Slot *mod_slot;
    }
    Py_ssize_t remaining;
    uint8_t kind;
    uint8_t zero_terminated;
} _PySlotIterator_state;

typedef struct {
    _PySlot_Iterator_state states[_PySlot_MAX_RECURSION];
    uint8_t recursion_level;
} _PySlotIterator;

PyAPI_FUNC(int) _PySlotIterator_Init(_PySlotIterator *, int kind);
PyAPI_FUNC(int) _PySlotIterator_Next(_PySlotIterator *);


#endif // _Py_PYCORE_SLOTS_H
