#ifndef _Py_PYCORE_SLOTS_H
#define _Py_PYCORE_SLOTS_H

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

#include <stdbool.h>

#define _PySlot_TYPE_VOID 1
#define _PySlot_TYPE_FUNC 2
#define _PySlot_TYPE_PTR 3
#define _PySlot_TYPE_SIZE 4
#define _PySlot_TYPE_INT64 5
#define _PySlot_TYPE_UINT64 6

#define _PySlot_KIND_TYPE 1
#define _PySlot_KIND_MOD 2
#define _PySlot_KIND_COMPAT 0x10
#define _PySlot_KIND_SLOT 0x20

#define _PySlot_NULL_DEPRECATED 0
#define _PySlot_NULL_REJECT 1
#define _PySlot_NULL_ALLOW  2

typedef struct {
    const char *name;
    uint8_t dtype;
    uint8_t kind;
    uint8_t null_handling;  // for pointers (incl. functions)
    bool subslots :1;
    bool reject_duplicates :1;
    bool deprecate_duplicates :1;
    bool is_name :1;
    union {
        struct {
            /* For type slots (_PySlot_KIND_TYPE):
             * Most slots corresponds to members in PyTypeObject & similar
             * structs.
             * Each entry has two offsets, "slot_offset" and "subslot_offset".
             * If is subslot_offset is -1, slot_offset is an offset within the
             * PyTypeObject struct.
             * Otherwise slot_offset is an offset to a pointer to a sub-slots
             * struct (such as "tp_as_number"), and subslot_offset is the
             * offset within that struct.
             *
             * If both are zero, the slot needs special handling; that is,
             * the offset mechanism isn't used.
             */
            short subslot_offset;
            short slot_offset;
        } type_info;
        struct {
            /* For compat slots (_PySlot_KIND_COMPAT):
             * these slots were renumbered; `type_id` is the ID of the new
             * type slot; `mod_id` of the module slot.
             */
            uint8_t type_id;
            uint8_t mod_id;
        } compat_info;
    };
} _PySlot_Info;

// The actual table is generated by a script.
extern _PySlot_Info _PySlot_InfoTable[];

#define _PySlot_MAX_NESTING 5

typedef struct {
    union {
        // tagged by slot_struct_kind:
        PySlot *slot;               // with _PySlot_KIND_SLOT
        PyType_Slot *tp_slot;       // with _PySlot_KIND_TYPE
        PyModuleDef_Slot *mod_slot; // with _PySlot_KIND_MOD
    };
    Py_ssize_t remaining;
    uint8_t slot_struct_kind;
    bool zero_terminated :1;
    bool ignoring_fallbacks :1;
} _PySlotIterator_state;

typedef struct {
    _PySlotIterator_state *state;
    _PySlotIterator_state states[_PySlot_MAX_NESTING];
    uint8_t kind;
    uint8_t recursion_level;
    unsigned int seen[_Py_slot_COUNT / sizeof(unsigned int) + 1];

    // Output information:
    const _PySlot_Info *info;
    PySlot current;
    char *name;
} _PySlotIterator;

PyAPI_FUNC(int) _PySlotIterator_InitWithKind(
    _PySlotIterator *, PySlot*, Py_ssize_t n_slots,
    int result_kind, int slot_struct_kind);
#define _PySlotIterator_Init(I, S, N, K) \
    _PySlotIterator_InitWithKind(I, S, N, K, _PySlot_KIND_SLOT)
PyAPI_FUNC(int) _PySlotIterator_Next(_PySlotIterator *);

/* Raise (and return -1) if given slot is duplicate but shouldn't. */
PyAPI_FUNC(int) _PySlotIterator_ValidateCurrentSlot(_PySlotIterator *);

/* Return 1 if given slot was "seen" by a RejectDuplicate call. */
PyAPI_FUNC(bool) _PySlotIterator_SawSlot(_PySlotIterator *, int);

#endif // _Py_PYCORE_SLOTS_H
