import re
import sys
from collections import defaultdict
import unicodedata as unicodedata_current
from unicodedata import ucd_3_2_0 as unicodedata_320

def compact_set(elements, line_length=0):
    """Return the representation of a set with the given integer elements"""
    elements = sorted(elements)
    if not elements:
        return "set()"
    entries = []
    def add_range(first, last):
        r = range(first, last + 1)
        if len(r) <= 3:
            # 3 or fewer items are listed individually
            for e in r:
                entries.append(str(e))
        else:
            entries.append(f'*{r}')
    first = last = None
    for element in elements:
        if first is None:
            first = last = element
        elif element == last + 1:
            last += 1
        else:
            add_range(first, last)
            first = last = element
    add_range(first, last)
    return '{' + line_wrap_items(entries, line_length+1) + '}'

def line_wrap_items(items, line_length):
    result = ['']
    for item in items:
        if line_length + len(item) >= 79:
            result[-1] = result[-1].strip()
            result.append('\n    ')
            line_length = 4
        result.append(item + ', ')
        line_length += len(item) + 2
    result[-1] = result[-1].strip(', ')
    return ''.join(result)

############## Read the tables in the RFC #######################

with open("Tools/unicode/data/rfc3454.txt", encoding='utf-8') as data_file:
    data = data_file.readlines()

tables = []
table_titles = {}
curname = None
for l in data:
    l = l.strip()
    if not l:
        continue
    # Skip RFC page breaks
    if l.startswith(("Hoffman & Blanchet", "RFC 3454")):
        continue
    # Find appendix section titles
    m = re.fullmatch("([A-Z](.[0-9])+) (.*)", l)
    if m:
        table_titles[m[1].replace('.', '').lower()] = m[0]
    # Find start/end lines
    m = re.fullmatch("----- (Start|End) Table ([A-Z](.[0-9])+) -----", l)
    if m:
        if m.group(1) == "Start":
            if curname:
                raise RuntimeError("Double Start", (curname, l))
            curname = m.group(2)
            table = {}
            tables.append((curname, table))
            continue
        else:
            if not curname:
                raise RuntimeError("End without start", l)
            if curname != m.group(2):
                raise RuntimeError("Unexpected end", l)
            curname = None
            continue
    if not curname:
        continue
    # Now we are in a table
    fields = l.split(";")
    if len(fields) > 1:
        # Drop comment field
        fields = fields[:-1]
    if len(fields) == 1:
        fields = fields[0].split("-")
        if len(fields) > 1:
            # range
            try:
                start, end = fields
            except ValueError:
                raise RuntimeError("Unpacking problem", l)
        else:
            start = end = fields[0]
        start = int(start, 16)
        end = int(end, 16)
        for i in range(start, end+1):
            table[i] = i
    else:
        code, value = fields
        value = value.strip()
        if value:
            value = [int(v, 16) for v in value.split(" ")]
        else:
            # table B.1
            value = None
        table[int(code, 16)] = value

# Keep a copy for later
orig_tables = list(tables)

# Make pop() start with the first one
tables.reverse()

def pop_table(expected_name):
    """Pop the next table and assert it has the given name"""
    name, table = tables.pop()
    assert name == expected_name
    return table

########### Helpers for printing out Python functions #############

results = []
def output(*strings, end='\n'):
    content = ' '.join(strings) + end
    print(content, end='')
    results.append(content)

def output_in_table_head(name):
    output(f'def in_table_{name}(code):')
    if title := table_titles.get(name):
        output(f'    {"Lookup in RFC 3454 " + title!r}')

def output_in_table_function(name, table, code=None, **ns):
    print(f'Generating table {name}', file=sys.stderr)
    output()
    if code is not None:
        output_in_table_head(name)
        output(code.strip('\n'))
    else:
        lower = min(table)
        upper = max(table) + 1
        if len(table) == upper - lower:
            assert set(table) == set(range(lower, upper))
            output_in_table_head(name)
            output(f'    return ord(code) in range({lower:#x}, {upper:#x})')
        else:
            output(f'_{name}_set = frozenset({compact_set(table, 20)})')
            output_in_table_head(name)
            output(f'    return ord(code) in _{name}_set')
    output()

########### Generate compact Python versions of the tables #############

output("""# This file is generated by mkstringprep.py. DO NOT EDIT.
\"\"\"Library that exposes various tables found in the StringPrep RFC 3454.

There are two kinds of tables: sets, for which a member test is provided,
and mappings, for which a mapping function is provided.
\"\"\"

# This check asserts that mkstringprep.py has been run
# when unicodedata is modified to ensure conformant behavior.
import unicodedata
""")

output("assert unicodedata.unidata_version == %r" % (unicodedata_current.unidata_version,))

output("""
from unicodedata import ucd_3_2_0 as unicodedata_320
""")

output("assert unicodedata_320.unidata_version == %r" % (unicodedata_320.unidata_version,))

# A.1 is the table of unassigned characters
table = pop_table("A.1")
output_in_table_function('a1', table, """
    if unicodedata_320.category(code) != 'Cn': return False
    c = ord(code)
    if 0xFDD0 <= c < 0xFDF0: return False
    return (c & 0xFFFF) not in (0xFFFE, 0xFFFF)
""")

# B.1 cannot easily be derived
table = pop_table("B.1")
output_in_table_function('b1', table)

# B.2 and B.3 is case folding.
# It takes CaseFolding.txt into account, which is
# not available in the Python database. Since
# B.2 is derived from B.3, we process B.3 first.
# B.3 supposedly *is* CaseFolding-3.2.0.txt.

table_b2 = pop_table("B.2")
table_b3 = pop_table("B.3")

# B.3 is mostly Python's .lower, except for a number
# of special cases, e.g. considering canonical forms.
# To enforce Unicode 3.2.0 behavior of .lower instead of
# whatever Unicode version is included with Python we
# add unassigned or newly case-folding codepoints to
# the exception map, too.

b3_exceptions = {}
b3_identities = []

for k,v in table_b3.items():
    if list(map(ord, chr(k).lower())) != v:
        b3_exceptions[k] = "".join(map(chr,v))
for cp in range(0x110000):
    ch = chr(cp)
    # Assigned in current Unicode version
    # and supports case folding, but not
    # explicitly in B.2 or B.3 tables.
    if (unicodedata_current.category(ch) != "Cn"
            and ch.lower() != ch
            and cp not in table_b2
            and cp not in table_b3):
        b3_identities.append(cp)

b3 = sorted(b3_exceptions.items())

output("""
b3_exceptions = frozendict({
    """ + line_wrap_items((f"{k:#x}:{v!a}" for k, v in b3), 4) + """,
    **{cp: chr(cp) for cp in """ + compact_set(b3_identities, 32) + """}
})
""")

output("""
def map_table_b3(code):
    r = b3_exceptions.get(ord(code))
    if r is not None: return r
    return code.lower()
""")

def map_table_b3(code):
    r = b3_exceptions.get(ord(code))
    if r is not None: return r
    return code.lower()

# B.2 is case folding for NFKC. This is the same as B.3,
# except where NormalizeWithKC(Fold(a)) !=
# NormalizeWithKC(Fold(NormalizeWithKC(Fold(a))))

def map_table_b2(a):
    al = map_table_b3(a)
    b = unicodedata_320.normalize("NFKC", al)
    bl = "".join([map_table_b3(ch) for ch in b])
    c = unicodedata_320.normalize("NFKC", bl)
    if b != c:
        return c
    else:
        return al

specials = {}
for k,v in table_b2.items():
    if list(map(ord, map_table_b2(chr(k)))) != v:
        specials[k] = v

# B.3 should not add any additional special cases
assert specials == {}

output("""
def map_table_b2(a):
    al = map_table_b3(a)
    b = unicodedata_320.normalize("NFKC", al)
    bl = "".join([map_table_b3(ch) for ch in b])
    c = unicodedata_320.normalize("NFKC", bl)
    if b != c:
        return c
    else:
        return al
""")

# C.1.1 is a table with a single character
table = c11_table = pop_table("C.1.1")
output_in_table_function('c11', table, """
    return code == " "
""")

# C.1.2 is the rest of all space characters
table = pop_table("C.1.2")
table = set(table)

output_in_table_function('c12', table, """
    return unicodedata_320.category(code) == "Zs" and code != " "
""")
output_in_table_function('c1', table | set(c11_table), """
    return unicodedata_320.category(code) == "Zs"
""")

# C.2.1 ASCII control characters
table_c21 = pop_table("C.2.1")
table_c21 = set(table_c21)
output_in_table_function('c21', table_c21, """
    return ord(code) < 128 and unicodedata_320.category(code) == "Cc"
""")

# C.2.2 Non-ASCII control characters. It also includes
# a number of characters in category Cf.
table_c22 = pop_table("C.2.2")
table_c22 = set(table_c22)

specials = {
    c for c in table_c22
    if c > 127 and unicodedata_320.category(chr(c)) != "Cc"
}
output("_c22_specials = " + compact_set(specials))

output_in_table_function('c22', table_c22, """
    c = ord(code)
    if c < 128: return False
    if unicodedata_320.category(code) == "Cc": return True
    return c in _c22_specials
""", _c22_specials=specials)

output_in_table_function('c2', table_c21 | table_c22, """
    return unicodedata_320.category(code) == "Cc" or \\
           ord(code) in _c22_specials
""", _c22_specials=specials)

# C.3 Private use
table = pop_table("C.3")
output_in_table_function('c3', table, """
    return unicodedata_320.category(code) == "Co"
""")

# C.4 Non-character code points, xFFFE, xFFFF
# plus process internal codes
table = pop_table("C.4")
output_in_table_function('c4', table, """
    c = ord(code)
    if c < 0xFDD0: return False
    if c < 0xFDF0: return True
    return (ord(code) & 0xFFFF) in (0xFFFE, 0xFFFF)
""")

# C.5 Surrogate codes
table = pop_table("C.5")
output_in_table_function('c5', table, """
    return unicodedata_320.category(code) == "Cs"
""")

# C.6 Inappropriate for plain text
table = pop_table("C.6")
output_in_table_function('c6', table)

# C.7 Inappropriate for canonical representation
table = pop_table("C.7")
output_in_table_function('c7', table)

# C.8 Change display properties or are deprecated
table = pop_table("C.8")
output_in_table_function('c8', table)

# C.9 Tagging characters
table = pop_table("C.9")
output_in_table_function('c9', table)

# D.1 Characters with bidirectional property "R" or "AL"
table = pop_table("D.1")
output_in_table_function('d1', table, """
    return unicodedata_320.bidirectional(code) in ("R","AL")
""")

# D.2 Characters with bidirectional property "L"
table = pop_table("D.2")
output_in_table_function('d2', table, """
    return unicodedata_320.bidirectional(code) == "L"
""")

# All tables should be included now
assert not tables


########### Backwards compatibility #############

output("""
def __getattr__(name):
    if name.endswith(('_set', '_specials')):
        func_name = 'in_table_' + name.removesuffix('_set').removesuffix('_specials')
        func = globals().get(func_name)
        if func:
            import warnings
            set = {i for i in range(0x11_0000) if func(chr(i))}
            globals()[name] = set
            warnings._deprecated(
                'stringprep.' + name,
                remove=(3, 21),
                message=f'{name} and other undocumented stringprep constants '
                    + 'will be removed in Python {remove}. '
                    + f'Use stringprep.{func_name}() instead.',
                )
            return set
    raise AttributeError(name)
""", end="")
sys.stdout.flush()


########### Verification #############

result = ''.join(results)
namespace = {}
exec(result, namespace)

for name, table in orig_tables:
    identifier = name.lower().replace('.', '')
    if func := namespace.get('in_table_' + identifier):
        assert ('map_table_' + identifier) not in namespace
        want = table.__contains__
    else:
        func = namespace['map_table_' + identifier]
        want = lambda i: ''.join(chr(c) for c in table.get(i, [i]))

    print(f'Exhaustively verifying table {name} to {func.__name__}', file=sys.stderr)
    for i in range(0x11_0000):
        c = chr(i)
        got = func(c)
        expected = want(i)
        assert got == expected, f'{i:#x} {got} != {expected}'
        if i % 12345 == 0:
            print(f'{i:#x} {i/0x11_0000:.0%}', end='\r', flush=True, file=sys.stderr)
    print(f'              ', end='\r', file=sys.stderr, flush=True)
