# This file is generated by mkstringprep.py. DO NOT EDIT.
"""Library that exposes various tables found in the StringPrep RFC 3454.

There are two kinds of tables: sets, for which a member test is provided,
and mappings, for which a mapping function is provided.
"""

# This check asserts that mkstringprep.py has been run
# when unicodedata is modified to ensure conformant behavior.
import unicodedata

assert unicodedata.unidata_version == '18.0.0'

from unicodedata import ucd_3_2_0 as unicodedata_320

assert unicodedata_320.unidata_version == '3.2.0'

def in_table_a1(code):
    'Lookup in RFC 3454 A.1 Unassigned code points in Unicode 3.2'
    if unicodedata_320.category(code) != 'Cn': return False
    c = ord(code)
    if 0xFDD0 <= c < 0xFDF0: return False
    return (c & 0xFFFF) not in (0xFFFE, 0xFFFF)


_b1_set = frozenset({173, 847, 6150, 6155, 6156, 6157, 8203, 8204, 8205, 8288,
    *range(65024, 65040), 65279})
def in_table_b1(code):
    'Lookup in RFC 3454 B.1 Commonly mapped to nothing'
    return ord(code) in _b1_set


b3_exceptions = frozendict({
    0xb5:'\u03bc', 0xdf:'ss', 0x149:'\u02bcn', 0x17f:'s', 0x1f0:'j\u030c',
    0x345:'\u03b9', 0x390:'\u03b9\u0308\u0301', 0x3b0:'\u03c5\u0308\u0301',
    0x3c2:'\u03c3', 0x3d0:'\u03b2', 0x3d1:'\u03b8', 0x3d5:'\u03c6',
    0x3d6:'\u03c0', 0x3f0:'\u03ba', 0x3f1:'\u03c1', 0x3f2:'\u03c3',
    0x3f5:'\u03b5', 0x587:'\u0565\u0582', 0x1e96:'h\u0331', 0x1e97:'t\u0308',
    0x1e98:'w\u030a', 0x1e99:'y\u030a', 0x1e9a:'a\u02be', 0x1e9b:'\u1e61',
    0x1f50:'\u03c5\u0313', 0x1f52:'\u03c5\u0313\u0300',
    0x1f54:'\u03c5\u0313\u0301', 0x1f56:'\u03c5\u0313\u0342',
    0x1f80:'\u1f00\u03b9', 0x1f81:'\u1f01\u03b9', 0x1f82:'\u1f02\u03b9',
    0x1f83:'\u1f03\u03b9', 0x1f84:'\u1f04\u03b9', 0x1f85:'\u1f05\u03b9',
    0x1f86:'\u1f06\u03b9', 0x1f87:'\u1f07\u03b9', 0x1f88:'\u1f00\u03b9',
    0x1f89:'\u1f01\u03b9', 0x1f8a:'\u1f02\u03b9', 0x1f8b:'\u1f03\u03b9',
    0x1f8c:'\u1f04\u03b9', 0x1f8d:'\u1f05\u03b9', 0x1f8e:'\u1f06\u03b9',
    0x1f8f:'\u1f07\u03b9', 0x1f90:'\u1f20\u03b9', 0x1f91:'\u1f21\u03b9',
    0x1f92:'\u1f22\u03b9', 0x1f93:'\u1f23\u03b9', 0x1f94:'\u1f24\u03b9',
    0x1f95:'\u1f25\u03b9', 0x1f96:'\u1f26\u03b9', 0x1f97:'\u1f27\u03b9',
    0x1f98:'\u1f20\u03b9', 0x1f99:'\u1f21\u03b9', 0x1f9a:'\u1f22\u03b9',
    0x1f9b:'\u1f23\u03b9', 0x1f9c:'\u1f24\u03b9', 0x1f9d:'\u1f25\u03b9',
    0x1f9e:'\u1f26\u03b9', 0x1f9f:'\u1f27\u03b9', 0x1fa0:'\u1f60\u03b9',
    0x1fa1:'\u1f61\u03b9', 0x1fa2:'\u1f62\u03b9', 0x1fa3:'\u1f63\u03b9',
    0x1fa4:'\u1f64\u03b9', 0x1fa5:'\u1f65\u03b9', 0x1fa6:'\u1f66\u03b9',
    0x1fa7:'\u1f67\u03b9', 0x1fa8:'\u1f60\u03b9', 0x1fa9:'\u1f61\u03b9',
    0x1faa:'\u1f62\u03b9', 0x1fab:'\u1f63\u03b9', 0x1fac:'\u1f64\u03b9',
    0x1fad:'\u1f65\u03b9', 0x1fae:'\u1f66\u03b9', 0x1faf:'\u1f67\u03b9',
    0x1fb2:'\u1f70\u03b9', 0x1fb3:'\u03b1\u03b9', 0x1fb4:'\u03ac\u03b9',
    0x1fb6:'\u03b1\u0342', 0x1fb7:'\u03b1\u0342\u03b9', 0x1fbc:'\u03b1\u03b9',
    0x1fbe:'\u03b9', 0x1fc2:'\u1f74\u03b9', 0x1fc3:'\u03b7\u03b9',
    0x1fc4:'\u03ae\u03b9', 0x1fc6:'\u03b7\u0342', 0x1fc7:'\u03b7\u0342\u03b9',
    0x1fcc:'\u03b7\u03b9', 0x1fd2:'\u03b9\u0308\u0300',
    0x1fd3:'\u03b9\u0308\u0301', 0x1fd6:'\u03b9\u0342',
    0x1fd7:'\u03b9\u0308\u0342', 0x1fe2:'\u03c5\u0308\u0300',
    0x1fe3:'\u03c5\u0308\u0301', 0x1fe4:'\u03c1\u0313', 0x1fe6:'\u03c5\u0342',
    0x1fe7:'\u03c5\u0308\u0342', 0x1ff2:'\u1f7c\u03b9', 0x1ff3:'\u03c9\u03b9',
    0x1ff4:'\u03ce\u03b9', 0x1ff6:'\u03c9\u0342', 0x1ff7:'\u03c9\u0342\u03b9',
    0x1ffc:'\u03c9\u03b9', 0xfb00:'ff', 0xfb01:'fi', 0xfb02:'fl', 0xfb03:'ffi',
    0xfb04:'ffl', 0xfb05:'st', 0xfb06:'st', 0xfb13:'\u0574\u0576',
    0xfb14:'\u0574\u0565', 0xfb15:'\u0574\u056b', 0xfb16:'\u057e\u0576',
    0xfb17:'\u0574\u056d',
    **{cp: chr(cp) for cp in {570, 571, 573, 574, 577, *range(579, 583),
    584, 586, 588, 590, 880, 882, 886, 895, 975, 1015, 1017, 1018, 1021, 1022,
    1023, 1216, 1270, 1274, 1276, 1278, 1296, 1298, 1300, 1302, 1304, 1306,
    1308, 1310, 1312, 1314, 1316, 1318, 1320, 1322, 1324, 1326,
    *range(4256, 4294), 4295, 4301, *range(5024, 5110), 7305,
    *range(7312, 7355), 7357, 7358, 7359, 7838, 7930, 7932, 7934, 8498, 8579,
    *range(11264, 11312), 11360, 11362, 11363, 11364, 11367, 11369, 11371,
    *range(11373, 11377), 11378, 11381, 11390, 11391, 11392, 11394, 11396,
    11398, 11400, 11402, 11404, 11406, 11408, 11410, 11412, 11414, 11416,
    11418, 11420, 11422, 11424, 11426, 11428, 11430, 11432, 11434, 11436,
    11438, 11440, 11442, 11444, 11446, 11448, 11450, 11452, 11454, 11456,
    11458, 11460, 11462, 11464, 11466, 11468, 11470, 11472, 11474, 11476,
    11478, 11480, 11482, 11484, 11486, 11488, 11490, 11499, 11501, 11506,
    42560, 42562, 42564, 42566, 42568, 42570, 42572, 42574, 42576, 42578,
    42580, 42582, 42584, 42586, 42588, 42590, 42592, 42594, 42596, 42598,
    42600, 42602, 42604, 42624, 42626, 42628, 42630, 42632, 42634, 42636,
    42638, 42640, 42642, 42644, 42646, 42648, 42650, 42786, 42788, 42790,
    42792, 42794, 42796, 42798, 42802, 42804, 42806, 42808, 42810, 42812,
    42814, 42816, 42818, 42820, 42822, 42824, 42826, 42828, 42830, 42832,
    42834, 42836, 42838, 42840, 42842, 42844, 42846, 42848, 42850, 42852,
    42854, 42856, 42858, 42860, 42862, 42873, 42875, 42877, 42878, 42880,
    42882, 42884, 42886, 42891, 42893, 42896, 42898, 42902, 42904, 42906,
    42908, 42910, 42912, 42914, 42916, 42918, 42920, *range(42922, 42927),
    *range(42928, 42933), 42934, 42936, 42938, 42940, 42942, 42944, 42946,
    *range(42948, 42952), 42953, 42955, 42956, 42958, 42960, 42962, 42964,
    42966, 42968, 42970, 42972, 42973, 42978, 42997, 43884, 43885, 66598,
    66599, *range(66736, 66772), *range(66928, 66939), *range(66940, 66955),
    *range(66956, 66963), 66964, 66965, *range(68736, 68787),
    *range(68944, 68966), *range(71840, 71872), *range(93760, 93792),
    *range(93856, 93881), 122688, 122696, 122698, 122701, 122705, 122728,
    122730, 122732, 122734, 122738, 122740, 122742, 122744, 122746, 122748,
    122750, *range(125184, 125218)}}
})


def map_table_b3(code):
    r = b3_exceptions.get(ord(code))
    if r is not None: return r
    return code.lower()


def map_table_b2(a):
    al = map_table_b3(a)
    b = unicodedata_320.normalize("NFKC", al)
    bl = "".join([map_table_b3(ch) for ch in b])
    c = unicodedata_320.normalize("NFKC", bl)
    if b != c:
        return c
    else:
        return al


def in_table_c11(code):
    'Lookup in RFC 3454 C.1.1 ASCII space characters'
    return code == " "


def in_table_c12(code):
    'Lookup in RFC 3454 C.1.2 Non-ASCII space characters'
    return unicodedata_320.category(code) == "Zs" and code != " "


def in_table_c1(code):
    'Lookup in RFC 3454 C.1 Space characters'
    return unicodedata_320.category(code) == "Zs"


def in_table_c21(code):
    'Lookup in RFC 3454 C.2.1 ASCII control characters'
    return ord(code) < 128 and unicodedata_320.category(code) == "Cc"

_c22_specials = {1757, 1807, 6158, 8204, 8205, 8232, 8233, *range(8288, 8292),
    *range(8298, 8304), 65279, *range(65529, 65533), *range(119155, 119163)}

def in_table_c22(code):
    'Lookup in RFC 3454 C.2.2 Non-ASCII control characters'
    c = ord(code)
    if c < 128: return False
    if unicodedata_320.category(code) == "Cc": return True
    return c in _c22_specials


def in_table_c2(code):
    'Lookup in RFC 3454 C.2 Control characters'
    return unicodedata_320.category(code) == "Cc" or \
           ord(code) in _c22_specials


def in_table_c3(code):
    'Lookup in RFC 3454 C.3 Private use'
    return unicodedata_320.category(code) == "Co"


def in_table_c4(code):
    'Lookup in RFC 3454 C.4 Non-character code points'
    c = ord(code)
    if c < 0xFDD0: return False
    if c < 0xFDF0: return True
    return (ord(code) & 0xFFFF) in (0xFFFE, 0xFFFF)


def in_table_c5(code):
    'Lookup in RFC 3454 C.5 Surrogate codes'
    return unicodedata_320.category(code) == "Cs"


def in_table_c6(code):
    'Lookup in RFC 3454 C.6 Inappropriate for plain text'
    return ord(code) in range(0xfff9, 0xfffe)


def in_table_c7(code):
    'Lookup in RFC 3454 C.7 Inappropriate for canonical representation'
    return ord(code) in range(0x2ff0, 0x2ffc)


_c8_set = frozenset({832, 833, 8206, 8207, *range(8234, 8239),
    *range(8298, 8304)})
def in_table_c8(code):
    'Lookup in RFC 3454 C.8 Change display properties or are deprecated'
    return ord(code) in _c8_set


_c9_set = frozenset({917505, *range(917536, 917632)})
def in_table_c9(code):
    'Lookup in RFC 3454 C.9 Tagging characters'
    return ord(code) in _c9_set


def in_table_d1(code):
    'Lookup in RFC 3454 D.1 Characters with bidirectional property "R" or "AL"'
    return unicodedata_320.bidirectional(code) in ("R","AL")


def in_table_d2(code):
    'Lookup in RFC 3454 D.2 Characters with bidirectional property "L"'
    return unicodedata_320.bidirectional(code) == "L"


def __getattr__(name):
    if name.endswith(('_set', '_specials')):
        func_name = 'in_table_' + name.removesuffix('_set').removesuffix('_specials')
        func = globals().get(func_name)
        if func:
            import warnings
            set = {i for i in range(0x11_0000) if func(chr(i))}
            globals()[name] = set
            warnings._deprecated(
                'stringprep.' + name,
                remove=(3, 21),
                message=f'{name} and other undocumented stringprep constants '
                    + 'will be removed in Python {remove}. '
                    + f'Use stringprep.{func_name}() instead.',
                )
            return set
    raise AttributeError(name)
