"""Generate the repetitive parts of handling individual C types

Usage: python Modules/_ctypes/gen_cfield.py > Modules/_ctypes/gen_cfield.inc
"""
from struct import calcsize
from array import array
import ctypes
from dataclasses import dataclass
from itertools import product
from functools import cached_property
from textwrap import dedent

print('/* Generated by Modules/_ctypes/gen_cfield.py */')

@dataclass
class FixedTypeInfo:
    nbytes: int
    is_signed: bool

    @cached_property
    def nbits(self):
        """Number of bits"""
        return self.nbytes * 8

    @cached_property
    def c_type(self):
        """C type name, like int32_t or uint64_t"""
        sgn = '' if tp.is_signed else 'u'
        return f'{sgn}int{self.nbits}_t'

    @cached_property
    def type_tag(self):
        """Short type tag, like i32 or u64"""
        sgn = 's' if tp.is_signed else 'u'
        return f'{sgn}{self.nbits}'

def digraphs_to_braces(code):
    return code.replace('<%', '{').replace('%>', '}')

FIXED_TYPES = [FixedTypeInfo(b, s) for b, s in product(
    (1, 2, 4, 8),
    (False, True),
)]

for tp in FIXED_TYPES:
    pyapi_type = f'{'' if tp.is_signed else 'U'}Int{max(32, tp.nbits)}'
    print(digraphs_to_braces(dedent(f'''\
        static PyObject *
        {tp.type_tag}_set(void *ptr, PyObject *value, Py_ssize_t size)
        <%
            assert(NUM_BITS(size) || (size == {tp.nbytes}));
            {tp.c_type} val;
            if (PyLong_Check(value)
                    && PyUnstable_Long_IsCompact((PyLongObject *)value)) <%
                val = ({tp.c_type})PyUnstable_Long_CompactValue(
                    (PyLongObject *)value);
            %>
            else <%
                int res = PyLong_AsNativeBytes(
                    value, &val, {tp.nbytes}, Py_ASNATIVEBYTES_DEFAULTS);
                if (res < 0) <%
                    return NULL;
                %>
            %>
            *({tp.c_type}*)ptr = SET({tp.c_type}, *({tp.c_type}*)ptr, val, size);
            _RET(value);
        %>

        static PyObject *
        {tp.type_tag}_get(void *ptr, Py_ssize_t size)
        <%
            assert(NUM_BITS(size) || (size == {tp.nbytes}));
            {tp.c_type} val;
            memcpy(&val, ptr, sizeof(val));
            GET_BITFIELD(val, size);
            return PyLong_From{pyapi_type}(val);
        %>
    ''')))
    if tp.nbytes == 1:
        continue
    print(digraphs_to_braces(dedent(f'''\
        static PyObject *
        {tp.type_tag}_set_sw(void *ptr, PyObject *value, Py_ssize_t size)
        <%
            {tp.c_type} val;
            PyObject *res = {tp.type_tag}_set(&val, value, size);
            if (res == NULL) <%
                return NULL;
            %>
            {tp.c_type} field;
            memcpy(&field, ptr, sizeof(field));
            field = _Py_bswap{tp.nbits}(field);
            field = SET({tp.c_type}, field, val, size);
            field = _Py_bswap{tp.nbits}(field);
            memcpy(ptr, &field, sizeof(field));
            _RET(value);
        %>

        static PyObject *
        {tp.type_tag}_get_sw(void *ptr, Py_ssize_t size)
        <%
            assert(NUM_BITS(size) || (size == {tp.nbytes}));
            {tp.c_type} val;
            memcpy(&val, ptr, sizeof(val));
            val = _Py_bswap{tp.nbits}(val);
            GET_BITFIELD(val, size);
            return PyLong_From{pyapi_type}(val);
        %>
    ''')))

@dataclass
class CTypeInfo:
    symbol: str
    c_type_name: str
    format_name: str = None
    swap: bool = None
    std_size: int = None
    condition: str = None
    ffi_type: str = None

    def __post_init__(self):
        if self.format_name is None:
            self.format_name = self.symbol
        if self.std_size is None:
            self.std_size = calcsize('=' + self.symbol)
        if self.ffi_type is None:
            raise ValueError('unknown ffi_type')

class PointerTypeInfo(CTypeInfo):
    def __post_init__(self):
        if self.std_size is None:
            self.std_size = ctypes.sizeof(ctypes.c_void_p)
        if self.swap is None:
            self.swap = False
        if self.ffi_type is None:
            self.ffi_type = 'ffi_type_pointer'
        super().__post_init__()

class IntegerTypeInfo(CTypeInfo):
    def __post_init__(self):
        super().__post_init__()
        if self.swap is None:
            self.swap = self.std_size > 1

class FloatptTypeInfo(CTypeInfo):
    pass


COMPLEX_IFDEF = 'defined(Py_HAVE_C_COMPLEX) && defined(Py_FFI_SUPPORT_C_COMPLEX)'

TYPEINFOS = [
    PointerTypeInfo('s', 'char *'),
    IntegerTypeInfo('b', 'signed char',
                    ffi_type='ffi_type_schar'),
    IntegerTypeInfo('B', 'unsigned char',
                    ffi_type='ffi_type_uchar'),
    IntegerTypeInfo('c', 'char',
                    ffi_type='ffi_type_schar'),
    FloatptTypeInfo('d', 'double', swap=True,
                    ffi_type='ffi_type_double'),
    FloatptTypeInfo('C', 'double complex',
                    std_size=calcsize('=dd'),
                    ffi_type='ffi_type_complex_double',
                    condition=COMPLEX_IFDEF),
    FloatptTypeInfo('E', 'float complex',
                    std_size=calcsize('=ff'),
                    ffi_type='ffi_type_complex_float',
                    condition=COMPLEX_IFDEF),
    FloatptTypeInfo('F', 'long double complex',
                    std_size=calcsize('=ff') * 2,
                    ffi_type='ffi_type_complex_longdouble',
                    condition=COMPLEX_IFDEF),
    IntegerTypeInfo('g', 'long double', swap=False,
                    std_size=calcsize('=d') * 2,
                    ffi_type='ffi_type_longdouble'),
    FloatptTypeInfo('f', 'float', swap=True,
                    ffi_type='ffi_type_float'),
    IntegerTypeInfo('h', 'short',
                    ffi_type='ffi_type_sshort'),
    IntegerTypeInfo('H', 'unsigned short',
                    ffi_type='ffi_type_ushort'),
    IntegerTypeInfo('i', 'int',
                    ffi_type='ffi_type_sint'),
    IntegerTypeInfo('I', 'unsigned int',
                    ffi_type='ffi_type_uint'),
    IntegerTypeInfo('l', 'long',
                    ffi_type='ctypes_ffi_type_slong'),
    IntegerTypeInfo('L', 'unsigned long',
                    ffi_type='ctypes_ffi_type_ulong'),
    IntegerTypeInfo('q', 'long long',
                    ffi_type='ctypes_ffi_type_slonglong'),
    IntegerTypeInfo('Q', 'unsigned long long',
                    ffi_type='ctypes_ffi_type_ulonglong'),
    PointerTypeInfo('P', 'void *'),
    PointerTypeInfo('z', 'char *'),
    CTypeInfo('u', 'wchar_t',
              std_size=array('h').itemsize,
              ffi_type='ctypes_ffi_type_wchar_t'),
    PointerTypeInfo('U', 'wchar_t *'),
    PointerTypeInfo('Z', 'wchar_t *'),
    PointerTypeInfo('X', 'BSTR', condition='defined(MS_WIN32)'),
    CTypeInfo('v', 'vBOOL', std_size=calcsize('=h'),
              ffi_type='ffi_type_sshort'),
    CTypeInfo('?', 'bool',
              format_name='bool',
              swap=True,
              std_size=calcsize('=b'),
              ffi_type='ctypes_ffi_type_bool'),
    PointerTypeInfo('O', 'PyObject *'),
]

current_condition = None
def start_condition(new_condition=None):
    global current_condition
    if new_condition != current_condition:
        if current_condition:
            print('#endif')
        if new_condition:
            print('#if ' + new_condition)
        current_condition = new_condition

print('struct formattable {')
for info in TYPEINFOS:
    start_condition(info.condition)
    print(f'    struct fielddesc fmt_{info.format_name};  // {info.c_type_name}')
start_condition()
print('};')
print()
print('static struct formattable formattable = {')
for info in TYPEINFOS:
    start_condition(info.condition)
    parts = [
        f"'{info.symbol}'",
        f"{info.format_name}_set",
        f"{info.format_name}_get",
        'NULL',
    ]
    if info.swap:
        parts.extend([
            f"{info.format_name}_set_sw",
            f"{info.format_name}_get_sw",
        ])
    fields = '{' + ', '.join(parts) + '}'
    print(f'    .fmt_{info.format_name} = {fields},')
start_condition(None)
print('};')
print('struct fielddesc *')
print('_ctypes_get_fielddesc(const char *fmt)')
print('{')
print('    static int initialized = 0;')
print('    if (!initialized) {')
print('        /* Delayed initialization. Windows cannot statically reference dynamically')
print('           loaded addresses from DLLs. */')
for info in TYPEINFOS:
    start_condition(info.condition)
    print(f'        formattable.fmt_{info.format_name}.pffi_type = &{info.ffi_type};')
start_condition(None)
print('        initialized = 1;')
print('    }')
print('    switch(fmt[0]) {')
for info in TYPEINFOS:
    start_condition(info.condition)
    print(f"        case '{info.symbol}': return &formattable.fmt_{info.format_name};")
start_condition(None)
print('    }')
print('    return NULL;')
print('}')
